const shortcuts = {
  common: [
    { keys: '⌘C',    desc: 'コピー',              cat: '編集' },
    { keys: '⌘V',    desc: 'ペースト',            cat: '編集' },
    { keys: '⌘X',    desc: 'カット',              cat: '編集' },
    { keys: '⌘Z',    desc: '元に戻す',            cat: '編集' },
    { keys: '⌘⇧Z',   desc: 'やり直す',            cat: '編集' },
    { keys: '⌘A',    desc: 'すべてを選択',        cat: '編集' },
    { keys: '⌘F',    desc: '検索',                cat: '編集' },
    { keys: '⌘S',    desc: '保存',                cat: 'ファイル' },
    { keys: '⌘N',    desc: '新規',                cat: 'ファイル' },
    { keys: '⌘O',    desc: '開く',                cat: 'ファイル' },
    { keys: '⌘W',    desc: 'ウィンドウを閉じる',  cat: 'ウィンドウ' },
    { keys: '⌘Q',    desc: '終了',                cat: 'ウィンドウ' },
    { keys: '⌘H',    desc: '非表示',              cat: 'ウィンドウ' },
    { keys: '⌘M',    desc: '最小化',              cat: 'ウィンドウ' },
    { keys: '⌘Tab',  desc: 'アプリ切り替え',      cat: 'システム' },
    { keys: '⌘Space',desc: 'Spotlight',           cat: 'システム' },
    { keys: '⌘⇧3',   desc: 'スクリーンショット（全画面）', cat: 'システム' },
    { keys: '⌘⇧4',   desc: 'スクリーンショット（選択）',   cat: 'システム' },
  ],
  finder: [
    { keys: '⌘N',    desc: '新しいFinderウィンドウ', cat: 'ファイル操作' },
    { keys: '⌘⇧N',   desc: '新しいフォルダ',        cat: 'ファイル操作' },
    { keys: '⌘⌫',    desc: 'ゴミ箱に入れる',        cat: 'ファイル操作' },
    { keys: '⌘D',    desc: '複製',                  cat: 'ファイル操作' },
    { keys: '⌘I',    desc: '情報を見る',            cat: 'ファイル操作' },
    { keys: 'Space', desc: 'クイックルック',        cat: 'ファイル操作' },
    { keys: '⌘1',    desc: 'アイコン表示',          cat: '表示' },
    { keys: '⌘2',    desc: 'リスト表示',            cat: '表示' },
    { keys: '⌘3',    desc: 'カラム表示',            cat: '表示' },
    { keys: '⌘4',    desc: 'ギャラリー表示',        cat: '表示' },
    { keys: '⌘↑',    desc: '上位フォルダを開く',    cat: '移動' },
    { keys: '⌘⇧G',   desc: 'フォルダへ移動',        cat: '移動' },
    { keys: '⌘⇧H',   desc: 'ホームフォルダ',        cat: '移動' },
    { keys: '⌘⇧D',   desc: 'デスクトップ',          cat: '移動' },
    { keys: '⌘⇧A',   desc: 'アプリケーション',      cat: '移動' },
  ],
  safari: [
    { keys: '⌘T',    desc: '新しいタブ',                cat: 'タブ' },
    { keys: '⌘W',    desc: 'タブを閉じる',              cat: 'タブ' },
    { keys: '⌘⇧T',   desc: '閉じたタブを開く',          cat: 'タブ' },
    { keys: '⌘⇧]',   desc: '次のタブ',                  cat: 'タブ' },
    { keys: '⌘⇧[',   desc: '前のタブ',                  cat: 'タブ' },
    { keys: '⌘R',    desc: '再読み込み',                cat: 'ナビゲーション' },
    { keys: '⌘L',    desc: 'アドレスバー',              cat: 'ナビゲーション' },
    { keys: '⌘[',    desc: '戻る',                      cat: 'ナビゲーション' },
    { keys: '⌘]',    desc: '進む',                      cat: 'ナビゲーション' },
    { keys: '⌘D',    desc: 'ブックマークに追加',        cat: 'ブックマーク' },
    { keys: '⌘+',    desc: '拡大',                      cat: '表示' },
    { keys: '⌘-',    desc: '縮小',                      cat: '表示' },
  ],
  chrome: [
    { keys: '⌘T',    desc: '新しいタブ',                cat: 'タブ' },
    { keys: '⌘W',    desc: 'タブを閉じる',              cat: 'タブ' },
    { keys: '⌘⇧T',   desc: '閉じたタブを開く',          cat: 'タブ' },
    { keys: '⌘⇧]',   desc: '次のタブ',                  cat: 'タブ' },
    { keys: '⌘⇧[',   desc: '前のタブ',                  cat: 'タブ' },
    { keys: '⌘R',    desc: '再読み込み',                cat: 'ナビゲーション' },
    { keys: '⌘L',    desc: 'アドレスバー',              cat: 'ナビゲーション' },
    { keys: '⌘[',    desc: '戻る',                      cat: 'ナビゲーション' },
    { keys: '⌘]',    desc: '進む',                      cat: 'ナビゲーション' },
    { keys: '⌘⇧N',   desc: 'シークレットウィンドウ',    cat: 'ウィンドウ' },
    { keys: '⌘⌥I',   desc: 'DevToolsを開く',            cat: '開発' },
    { keys: '⌘+',    desc: '拡大',                      cat: '表示' },
    { keys: '⌘-',    desc: '縮小',                      cat: '表示' },
  ],
  vscode: [
    { keys: '⌘P',    desc: 'クイックオープン',          cat: 'ファイル' },
    { keys: '⌘⇧P',   desc: 'コマンドパレット',          cat: 'ファイル' },
    { keys: '⌘B',    desc: 'サイドバー切り替え',        cat: '表示' },
    { keys: '⌘`',    desc: 'ターミナル切り替え',        cat: '表示' },
    { keys: '⌘⇧E',   desc: 'エクスプローラー',          cat: '表示' },
    { keys: '⌘⇧F',   desc: 'プロジェクト内検索',        cat: '表示' },
    { keys: '⌘/',    desc: 'コメント切り替え',          cat: '編集' },
    { keys: '⌥↑',    desc: '行を上に移動',              cat: '編集' },
    { keys: '⌥↓',    desc: '行を下に移動',              cat: '編集' },
    { keys: '⌘D',    desc: '次の選択に追加',            cat: '編集' },
    { keys: '⌘⇧K',   desc: '行を削除',                  cat: '編集' },
    { keys: 'F5',    desc: 'デバッグ開始',              cat: 'デバッグ' },
    { keys: 'F10',   desc: 'ステップオーバー',          cat: 'デバッグ' },
  ],
  terminal: [
    { keys: '⌘T',    desc: '新しいタブ',            cat: 'ウィンドウ' },
    { keys: '⌘N',    desc: '新しいウィンドウ',      cat: 'ウィンドウ' },
    { keys: '⌘K',    desc: 'クリア',                cat: 'ウィンドウ' },
    { keys: '⌃C',    desc: '中断',                  cat: 'プロセス' },
    { keys: '⌃Z',    desc: 'バックグラウンドへ',    cat: 'プロセス' },
    { keys: '⌃D',    desc: 'EOF / ログアウト',      cat: 'プロセス' },
    { keys: '⌃A',    desc: '行頭へ',                cat: 'カーソル' },
    { keys: '⌃E',    desc: '行末へ',                cat: 'カーソル' },
    { keys: '⌃U',    desc: '行全体を削除',          cat: 'カーソル' },
    { keys: '⌃K',    desc: 'カーソル以降を削除',    cat: 'カーソル' },
    { keys: '⌃R',    desc: 'コマンド履歴を検索',    cat: '履歴' },
  ],
  iterm: [
    { keys: '⌘D',    desc: '縦分割',                cat: 'ペイン' },
    { keys: '⌘⇧D',   desc: '横分割',                cat: 'ペイン' },
    { keys: '⌘⌥↑',   desc: '上のペインに移動',      cat: 'ペイン' },
    { keys: '⌘⌥↓',   desc: '下のペインに移動',      cat: 'ペイン' },
    { keys: '⌃C',    desc: '中断',                  cat: 'プロセス' },
    { keys: '⌃A',    desc: '行頭へ',                cat: 'カーソル' },
    { keys: '⌃E',    desc: '行末へ',                cat: 'カーソル' },
    { keys: '⌃R',    desc: 'コマンド履歴を検索',    cat: '履歴' },
  ],
  xcode: [
    { keys: '⌘B',    desc: 'ビルド',                    cat: 'ビルド' },
    { keys: '⌘R',    desc: '実行',                      cat: 'ビルド' },
    { keys: '⌘⇧K',   desc: 'クリーン',                  cat: 'ビルド' },
    { keys: '⌘.',    desc: '停止',                      cat: 'ビルド' },
    { keys: '⌘U',    desc: 'テスト実行',                cat: 'テスト' },
    { keys: '⌘⇧O',   desc: 'クイックオープン',          cat: 'ナビゲーション' },
    { keys: '⌘⇧F',   desc: 'プロジェクト内検索',        cat: '検索' },
    { keys: 'F5',    desc: 'デバッグ続行',              cat: 'デバッグ' },
    { keys: 'F6',    desc: 'ステップオーバー',          cat: 'デバッグ' },
  ],
};

module.exports = shortcuts;
